import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '../styles/HomeStyles/Home.module.css'
import Header from '../components/Header.js'
import Navigation from '../components/Navigation.js'
import Contact from '../components/HomeComponents/Contact.js'

const inter = Inter({ subsets: ['latin'] })

const headerContent = {
  title: 'Hey, I\'m Anshu', excerpt: 'A freelance engineer - welcome to my website!'
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Anshuman Sinha</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home}>
        <div>
          <Header headerContent={headerContent}/>
          <Navigation></Navigation>
          <Contact></Contact>
        </div>
      </main>
    </>
  )
}